In [4]:
import requests
import pandas as pd
import time

API_KEY = "6d0c90e0ba689394edec2004c587f13996dbc4c2b5773ffe25c5236cc93262fa"

headers = {
    "X-API-Key": API_KEY
}

url_locations = "https://api.openaq.org/v3/locations"

params = {
    "bbox": "-74.3,40.5,-73.6,41",
    "limit": 1000
}

response = requests.get(url_locations, headers=headers, params=params, timeout=20)
data = response.json()

locations = data.get("results", [])

sensor_ids = []

for loc in locations:
    for s in loc.get("sensors", []):
        sensor_ids.append(s["id"])

sensor_ids = list(set(sensor_ids))

print("Всего сенсоров:", len(sensor_ids))


def get_sensor_data(sensor_id):
    url = f"https://api.openaq.org/v3/sensors/{sensor_id}/days"

    params = {
        "date_from": "2024-01-01",
        "date_to": "2024-12-31",
        "limit": 1000
    }

    try:
        r = requests.get(url, headers=headers, params=params, timeout=15)

        if r.status_code != 200:
            print(f"Sensor {sensor_id} failed: {r.status_code}")
            return None

        data = r.json()

        results = data.get("results", [])
        if not results:
            return None

        df = pd.json_normalize(results)
        df["sensor_id"] = sensor_id

        return df

    except requests.exceptions.Timeout:
        print(f"Timeout sensor {sensor_id}")
        return None

    except Exception as e:
        print(f"Error sensor {sensor_id}: {e}")
        return None


all_data = []

max_sensors = len(sensor_ids)

for i, sid in enumerate(sensor_ids):

    print(f"Processing {i+1}/{max_sensors} → sensor {sid}")

    df = get_sensor_data(sid)

    if df is not None:
        all_data.append(df)

    time.sleep(0.1)


if all_data:
    final_df = pd.concat(all_data, ignore_index=True)
else:
    final_df = pd.DataFrame()

print("DONE")
print("Rows:", len(final_df))
print(final_df.head())

Всего сенсоров: 249
Processing 1/249 → sensor 1536
Processing 2/249 → sensor 11571202
Processing 3/249 → sensor 11074566
Processing 4/249 → sensor 11074571
Processing 5/249 → sensor 7979020
Processing 6/249 → sensor 11074572
Processing 7/249 → sensor 15101967
Processing 8/249 → sensor 15101968
Processing 9/249 → sensor 15101969
Processing 10/249 → sensor 15101970
Processing 11/249 → sensor 15101971
Processing 12/249 → sensor 10454036
Processing 13/249 → sensor 11074582
Processing 14/249 → sensor 13322774
Processing 15/249 → sensor 13322775
Processing 16/249 → sensor 11074585
Processing 17/249 → sensor 13322776
Processing 18/249 → sensor 10454043
Processing 19/249 → sensor 11074587
Processing 20/249 → sensor 13322777
Processing 21/249 → sensor 7971870
Processing 22/249 → sensor 13322778
Processing 23/249 → sensor 7254050
Processing 24/249 → sensor 13719588
Processing 25/249 → sensor 13719589
Processing 26/249 → sensor 13719590
Processing 27/249 → sensor 13719591
Processing 28/249 → sensor 13719592
Processing 29/249 → sensor 10454057
Processing 30/249 → sensor 7971373
Processing 31/249 → sensor 10454068
Processing 32/249 → sensor 3637
Processing 33/249 → sensor 3638
Processing 34/249 → sensor 3639
Processing 35/249 → sensor 3640
Processing 36/249 → sensor 7254073
Processing 37/249 → sensor 7763001
Processing 38/249 → sensor 7762999
Processing 39/249 → sensor 12178491
Processing 40/249 → sensor 7971901
Processing 41/249 → sensor 5077566
Processing 42/249 → sensor 10454078
Processing 43/249 → sensor 14536763
Processing 44/249 → sensor 14536764
Processing 45/249 → sensor 10454082
Processing 46/249 → sensor 14536765
Processing 47/249 → sensor 14536766
Processing 48/249 → sensor 14536767
Processing 49/249 → sensor 1097
Processing 50/249 → sensor 1098
Processing 51/249 → sensor 1099
Processing 52/249 → sensor 1102
Processing 53/249 → sensor 1103
Processing 54/249 → sensor 1106
Processing 55/249 → sensor 2644
Processing 56/249 → sensor 2645
Processing 57/249 → sensor 2646
Processing 58/249 → sensor 11571192
Processing 59/249 → sensor 4272224
Processing 60/249 → sensor 1121
Processing 61/249 → sensor 7970916
Processing 62/249 → sensor 1128
Processing 63/249 → sensor 7970930
Processing 64/249 → sensor 1143
Processing 65/249 → sensor 1145
Processing 66/249 → sensor 4272250
Processing 67/249 → sensor 1146
Processing 68/249 → sensor 1147
Processing 69/249 → sensor 11571199
Processing 70/249 → sensor 1152
Processing 71/249 → sensor 14904962
Processing 72/249 → sensor 14904963
Processing 73/249 → sensor 14904964
Processing 74/249 → sensor 14904965
Processing 75/249 → sensor 9648774
Processing 76/249 → sensor 14904966
Processing 77/249 → sensor 6530188
Processing 78/249 → sensor 13193868
Processing 79/249 → sensor 9648782
Processing 80/249 → sensor 9648783
Processing 81/249 → sensor 13193869
Processing 82/249 → sensor 4272273
Processing 83/249 → sensor 13193873
Processing 84/249 → sensor 13193874
Processing 85/249 → sensor 13193875
Processing 86/249 → sensor 13193876
Processing 87/249 → sensor 13193877
Processing 88/249 → sensor 13193870
Processing 89/249 → sensor 6530200
Processing 90/249 → sensor 13193872
Processing 91/249 → sensor 9648796
Processing 92/249 → sensor 1693
Processing 93/249 → sensor 671
Processing 94/249 → sensor 673
Processing 95/249 → sensor 674
Processing 96/249 → sensor 4272290
Processing 97/249 → sensor 15915685
Processing 98/249 → sensor 7970982
Processing 99/249 → sensor 15915686
Processing 100/249 → sensor 12212728
Processing 101/249 → sensor 15915687
Processing 102/249 → sensor 15915688
Processing 103/249 → sensor 9648811
Processing 104/249 → sensor 9648812
Processing 105/249 → sensor 12212729
Processing 106/249 → sensor 15915689
Processing 107/249 → sensor 12212730
Processing 108/249 → sensor 7978166
Processing 109/249 → sensor 7978193
Processing 110/249 → sensor 14152914
Processing 111/249 → sensor 14152915
Processing 112/249 → sensor 14152916
Processing 113/249 → sensor 14152917
Processing 114/249 → sensor 7971030
Processing 115/249 → sensor 14152918
Processing 116/249 → sensor 8520920
Processing 117/249 → sensor 2189530
Processing 118/249 → sensor 7815388
Processing 119/249 → sensor 7815389
Processing 120/249 → sensor 1758
Processing 121/249 → sensor 8520925
Processing 122/249 → sensor 4272352
Processing 123/249 → sensor 1761
Processing 124/249 → sensor 8520933
Processing 125/249 → sensor 8520935
Processing 126/249 → sensor 6530280
Processing 127/249 → sensor 8520936
Processing 128/249 → sensor 8520938
Processing 129/249 → sensor 6530283
Processing 130/249 → sensor 1777
Processing 131/249 → sensor 15102193
Processing 132/249 → sensor 15102194
Processing 133/249 → sensor 7897332
Processing 134/249 → sensor 15102195
Processing 135/249 → sensor 15102196
Processing 136/249 → sensor 15102197
Processing 137/249 → sensor 7897339
Processing 138/249 → sensor 12178175
Processing 139/249 → sensor 7972608
Processing 140/249 → sensor 7972609
Processing 141/249 → sensor 7971073
Processing 142/249 → sensor 12178176
Processing 143/249 → sensor 12178177
Processing 144/249 → sensor 12178178
Processing 145/249 → sensor 15422208
Processing 146/249 → sensor 15422209
Processing 147/249 → sensor 15422210
Processing 148/249 → sensor 15422211
Processing 149/249 → sensor 7971082
Processing 150/249 → sensor 2165515
Processing 151/249 → sensor 7897355
Processing 152/249 → sensor 7897354
Processing 153/249 → sensor 14349090
Processing 154/249 → sensor 14349091
Processing 155/249 → sensor 14349092
Processing 156/249 → sensor 14349093
Processing 157/249 → sensor 14349094
Processing 158/249 → sensor 7979816
Processing 159/249 → sensor 23341
Processing 160/249 → sensor 7971117
Processing 161/249 → sensor 4272431
Processing 162/249 → sensor 7971629
Processing 163/249 → sensor 7386938
Processing 164/249 → sensor 7979835
Processing 165/249 → sensor 13594426
Processing 166/249 → sensor 13594427
Processing 167/249 → sensor 7386942
Processing 168/249 → sensor 7972670
Processing 169/249 → sensor 7972671
Processing 170/249 → sensor 13594428
Processing 171/249 → sensor 13594429
Processing 172/249 → sensor 13594430
Processing 173/249 → sensor 7971145
Processing 174/249 → sensor 7971668
Processing 175/249 → sensor 7979861
Processing 176/249 → sensor 7972696
Processing 177/249 → sensor 10888539
Processing 178/249 → sensor 7979870
Processing 179/249 → sensor 7972703
Processing 180/249 → sensor 7972702
Processing 181/249 → sensor 13193871
Processing 182/249 → sensor 7972707
Processing 183/249 → sensor 10888556
Processing 184/249 → sensor 3950
Processing 185/249 → sensor 3951
Processing 186/249 → sensor 3952
Processing 187/249 → sensor 3953
Processing 188/249 → sensor 3954
Processing 189/249 → sensor 7979380
Processing 190/249 → sensor 10888566
Processing 191/249 → sensor 7979901
Processing 192/249 → sensor 10888578
Processing 193/249 → sensor 10888579
Processing 194/249 → sensor 7979909
Processing 195/249 → sensor 7979399
Processing 196/249 → sensor 10888589
Processing 197/249 → sensor 7979411
Processing 198/249 → sensor 7979412
Processing 199/249 → sensor 2780575
Processing 200/249 → sensor 15657375
Processing 201/249 → sensor 15657376
Processing 202/249 → sensor 7972258
Processing 203/249 → sensor 15657377
Processing 204/249 → sensor 15657378
Processing 205/249 → sensor 15657379
Processing 206/249 → sensor 15422212
Processing 207/249 → sensor 7971247
Processing 208/249 → sensor 25520
Processing 209/249 → sensor 7979444
Processing 210/249 → sensor 1662910
Processing 211/249 → sensor 7971262
Processing 212/249 → sensor 7972295
Processing 213/249 → sensor 4272080
Processing 214/249 → sensor 13071824
Processing 215/249 → sensor 13071825
Processing 216/249 → sensor 7979475
Processing 217/249 → sensor 13071826
Processing 218/249 → sensor 13071827
Processing 219/249 → sensor 4272086
Processing 220/249 → sensor 13071828
Processing 221/249 → sensor 7971292
Processing 222/249 → sensor 10986460
Processing 223/249 → sensor 10986461
Processing 224/249 → sensor 10986463
Processing 225/249 → sensor 2016
Processing 226/249 → sensor 10986465
Processing 227/249 → sensor 2018
Processing 228/249 → sensor 10986466
Processing 229/249 → sensor 10986467
Processing 230/249 → sensor 10986462
Processing 231/249 → sensor 16083421
Processing 232/249 → sensor 16083422
Processing 233/249 → sensor 16083423
Processing 234/249 → sensor 16083424
Processing 235/249 → sensor 16083425
Processing 236/249 → sensor 7978991
Processing 237/249 → sensor 7324143
Processing 238/249 → sensor 7324145
Processing 239/249 → sensor 1522
Processing 240/249 → sensor 1523
Processing 241/249 → sensor 7971316
Processing 242/249 → sensor 12212726
Processing 243/249 → sensor 12212727
Processing 244/249 → sensor 7970808
Processing 245/249 → sensor 11571193
Processing 246/249 → sensor 11571194
Processing 247/249 → sensor 11571197
Processing 248/249 → sensor 1534
Processing 249/249 → sensor 1535
DONE
Rows: 30251
   value coordinates  flagInfo.hasFlags  parameter.id parameter.name  \
0  0.262        None              False             8             co
1  0.327        None              False             8             co
2  0.291        None              False             8             co
3  0.224        None              False             8             co
4  0.277        None              False             8             co

  parameter.units parameter.displayName period.label period.interval  \
0             ppm                  None         1day        24:00:00
1             ppm                  None         1day        24:00:00
2             ppm                  None         1day        24:00:00
3             ppm                  None         1day        24:00:00
4             ppm                  None         1day        24:00:00

  period.datetimeFrom.utc  ... coverage.expectedInterval  \
0    2024-01-01T05:00:00Z  ...                  24:00:00
1    2024-01-02T05:00:00Z  ...                  24:00:00
2    2024-01-03T05:00:00Z  ...                  24:00:00
3    2024-01-04T05:00:00Z  ...                  24:00:00
4    2024-01-05T05:00:00Z  ...                  24:00:00

  coverage.observedCount coverage.observedInterval  coverage.percentComplete  \
0                     21                  21:00:00                      88.0
1                     22                  22:00:00                      92.0
2                     22                  22:00:00                      92.0
3                     21                  21:00:00                      88.0
4                     22                  22:00:00                      92.0

   coverage.percentCoverage  coverage.datetimeFrom.utc  \
0                      88.0       2024-01-01T06:00:00Z
1                      92.0       2024-01-02T06:00:00Z
2                      92.0       2024-01-03T06:00:00Z
3                      88.0       2024-01-04T06:00:00Z
4                      92.0       2024-01-05T06:00:00Z

   coverage.datetimeFrom.local  coverage.datetimeTo.utc  \
0    2024-01-01T01:00:00-05:00     2024-01-02T05:00:00Z
1    2024-01-02T01:00:00-05:00     2024-01-03T05:00:00Z
2    2024-01-03T01:00:00-05:00     2024-01-04T05:00:00Z
3    2024-01-04T01:00:00-05:00     2024-01-05T05:00:00Z
4    2024-01-05T01:00:00-05:00     2024-01-06T05:00:00Z

   coverage.datetimeTo.local  sensor_id
0  2024-01-02T00:00:00-05:00       1536
1  2024-01-03T00:00:00-05:00       1536
2  2024-01-04T00:00:00-05:00       1536
3  2024-01-05T00:00:00-05:00       1536
4  2024-01-06T00:00:00-05:00       1536

[5 rows x 33 columns]

In [5]:
final_df["date"] = pd.to_datetime(final_df["coverage.datetimeTo.utc"])

final_df["parameter"] = final_df["parameter.name"]

aq = final_df[[
    "sensor_id",
    "date",
    "parameter",
    "value"
]].copy()

aq

       sensor_id                      date parameter   value
0           1536 2024-01-02 05:00:00+00:00        co  0.2620
1           1536 2024-01-03 05:00:00+00:00        co  0.3270
2           1536 2024-01-04 05:00:00+00:00        co  0.2910
3           1536 2024-01-05 05:00:00+00:00        co  0.2240
4           1536 2024-01-06 05:00:00+00:00        co  0.2770
...          ...                       ...       ...     ...
30246       1535 2024-12-28 05:00:00+00:00       no2  0.0397
30247       1535 2024-12-29 04:00:00+00:00       no2  0.0425
30248       1535 2024-12-30 05:00:00+00:00       no2  0.0233
30249       1535 2024-12-31 05:00:00+00:00       no2  0.0112
30250       1535 2025-01-01 05:00:00+00:00       no2  0.0187

[30251 rows x 4 columns]

In [6]:
response = requests.get(url_locations, headers=headers, params=params)
data = response.json()

locations = data["results"]

In [7]:
locations_list = []

for loc in locations:
    if loc.get("coordinates") and "sensors" in loc:
        for s in loc["sensors"]:
            locations_list.append({
                "sensor_id": s["id"],
                "lat": loc["coordinates"]["latitude"],
                "lon": loc["coordinates"]["longitude"],
                "location": loc["name"]})

locations_df = pd.DataFrame(locations_list)
locations_df

     sensor_id        lat        lon                               location
0          671  40.819700 -73.948100                                   CCNY
1          673  40.819700 -73.948100                                   CCNY
2          674  40.596900 -74.126400                           Susan Wagner
3         1097  40.849200 -73.931900                        Manhattan/IS143
4         1098  40.816101 -73.902199                           Bronx - IS52
..         ...        ...        ...                                    ...
244   16083421  40.810157 -73.960457  Teachers College, Columbia University
245   16083422  40.810157 -73.960457  Teachers College, Columbia University
246   16083423  40.810157 -73.960457  Teachers College, Columbia University
247   16083424  40.810157 -73.960457  Teachers College, Columbia University
248   16083425  40.810157 -73.960457  Teachers College, Columbia University

[249 rows x 4 columns]

In [8]:
final_df["date"] = pd.to_datetime(final_df["coverage.datetimeTo.utc"])

final_df["parameter"] = final_df["parameter.name"]

aq_df = final_df.merge(locations_df, on="sensor_id", how="left")
aq_df

,value,coordinates,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,period.label,period.interval,period.datetimeFrom.utc,...,coverage.datetimeFrom.utc,coverage.datetimeFrom.local,coverage.datetimeTo.utc,coverage.datetimeTo.local,sensor_id,date,parameter,lat,lon,location
0,0.2620,None,False,8,co,ppm,None,1day,24:00:00,2024-01-01T05:00:00Z,...,2024-01-01T06:00:00Z,2024-01-01T01:00:00-05:00,2024-01-02T05:00:00Z,2024-01-02T00:00:00-05:00,1536,2024-01-02 05:00:00+00:00,co,40.85355,-73.9661,Fort Lee Near Road
1,0.3270,None,False,8,co,ppm,None,1day,24:00:00,2024-01-02T05:00:00Z,...,2024-01-02T06:00:00Z,2024-01-02T01:00:00-05:00,2024-01-03T05:00:00Z,2024-01-03T00:00:00-05:00,1536,2024-01-03 05:00:00+00:00,co,40.85355,-73.9661,Fort Lee Near Road
2,0.2910,None,False,8,co,ppm,None,1day,24:00:00,2024-01-03T05:00:00Z,...,2024-01-03T06:00:00Z,2024-01-03T01:00:00-05:00,2024-01-04T05:00:00Z,2024-01-04T00:00:00-05:00,1536,2024-01-04 05:00:00+00:00,co,40.85355,-73.9661,Fort Lee Near Road
3,0.2240,None,False,8,co,ppm,None,1day,24:00:00,2024-01-04T05:00:00Z,...,2024-01-04T06:00:00Z,2024-01-04T01:00:00-05:00,2024-01-05T05:00:00Z,2024-01-05T00:00:00-05:00,1536,2024-01-05 05:00:00+00:00,co,40.85355,-73.9661,Fort Lee Near Road
4,0.2770,None,False,8,co,ppm,None,1day,24:00:00,2024-01-05T05:00:00Z,...,2024-01-05T06:00:00Z,2024-01-05T01:00:00-05:00,2024-01-06T05:00:00Z,2024-01-06T00:00:00-05:00,1536,2024-01-06 05:00:00+00:00,co,40.85355,-73.9661,Fort Lee Near Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30246,0.0397,None,False,7,no2,ppm,None,1day,24:00:00,2024-12-27T05:00:00Z,...,2024-12-27T06:00:00Z,2024-12-27T01:00:00-05:00,2024-12-28T05:00:00Z,2024-12-28T00:00:00-05:00,1535,2024-12-28 05:00:00+00:00,no2,40.85355,-73.9661,Fort Lee Near Road
30247,0.0425,None,False,7,no2,ppm,None,1day,24:00:00,2024-12-28T05:00:00Z,...,2024-12-28T06:00:00Z,2024-12-28T01:00:00-05:00,2024-12-29T04:00:00Z,2024-12-28T23:00:00-05:00,1535,2024-12-29 04:00:00+00:00,no2,40.85355,-73.9661,Fort Lee Near Road
30248,0.0233,None,False,7,no2,ppm,None,1day,24:00:00,2024-12-29T05:00:00Z,...,2024-12-29T09:00:00Z,2024-12-29T04:00:00-05:00,2024-12-30T05:00:00Z,2024-12-30T00:00:00-05:00,1535,2024-12-30 05:00:00+00:00,no2,40.85355,-73.9661,Fort Lee Near Road
30249,0.0112,None,False,7,no2,ppm,None,1day,24:00:00,2024-12-30T05:00:00Z,...,2024-12-30T06:00:00Z,2024-12-30T01:00:00-05:00,2024-12-31T05:00:00Z,2024-12-31T00:00:00-05:00,1535,2024-12-31 05:00:00+00:00,no2,40.85355,-73.9661,Fort Lee Near Road
30250,0.0187,None,False,7,no2,ppm,None,1day,24:00:00,2024-12-31T05:00:00Z,...,2024-12-31T06:00:00Z,2024-12-31T01:00:00-05:00,2025-01-01T05:00:00Z,2025-01-01T00:00:00-05:00,1535,2025-01-01 05:00:00+00:00,no2,40.85355,-73.9661,Fort Lee Near Road

In [9]:
aq = aq_df[[
    "sensor_id",
    "date",
    "parameter",
    "value",
    "lat",
    "lon",
    "location"]]
aq

,sensor_id,date,parameter,value,lat,lon,location
0,1536,2024-01-02 05:00:00+00:00,co,0.2620,40.85355,-73.9661,Fort Lee Near Road
1,1536,2024-01-03 05:00:00+00:00,co,0.3270,40.85355,-73.9661,Fort Lee Near Road
2,1536,2024-01-04 05:00:00+00:00,co,0.2910,40.85355,-73.9661,Fort Lee Near Road
3,1536,2024-01-05 05:00:00+00:00,co,0.2240,40.85355,-73.9661,Fort Lee Near Road
4,1536,2024-01-06 05:00:00+00:00,co,0.2770,40.85355,-73.9661,Fort Lee Near Road
...,...,...,...,...,...,...,...
30246,1535,2024-12-28 05:00:00+00:00,no2,0.0397,40.85355,-73.9661,Fort Lee Near Road
30247,1535,2024-12-29 04:00:00+00:00,no2,0.0425,40.85355,-73.9661,Fort Lee Near Road
30248,1535,2024-12-30 05:00:00+00:00,no2,0.0233,40.85355,-73.9661,Fort Lee Near Road
30249,1535,2024-12-31 05:00:00+00:00,no2,0.0112,40.85355,-73.9661,Fort Lee Near Road
30250,1535,2025-01-01 05:00:00+00:00,no2,0.0187,40.85355,-73.9661,Fort Lee Near Road

In [10]:
aq = aq[
    (aq["date"] >= "2024-01-01") &
    (aq["date"] < "2025-01-01")]
aq

,sensor_id,date,parameter,value,lat,lon,location
0,1536,2024-01-02 05:00:00+00:00,co,0.2620,40.85355,-73.9661,Fort Lee Near Road
1,1536,2024-01-03 05:00:00+00:00,co,0.3270,40.85355,-73.9661,Fort Lee Near Road
2,1536,2024-01-04 05:00:00+00:00,co,0.2910,40.85355,-73.9661,Fort Lee Near Road
3,1536,2024-01-05 05:00:00+00:00,co,0.2240,40.85355,-73.9661,Fort Lee Near Road
4,1536,2024-01-06 05:00:00+00:00,co,0.2770,40.85355,-73.9661,Fort Lee Near Road
...,...,...,...,...,...,...,...
30245,1535,2024-12-27 05:00:00+00:00,no2,0.0258,40.85355,-73.9661,Fort Lee Near Road
30246,1535,2024-12-28 05:00:00+00:00,no2,0.0397,40.85355,-73.9661,Fort Lee Near Road
30247,1535,2024-12-29 04:00:00+00:00,no2,0.0425,40.85355,-73.9661,Fort Lee Near Road
30248,1535,2024-12-30 05:00:00+00:00,no2,0.0233,40.85355,-73.9661,Fort Lee Near Road
30249,1535,2024-12-31 05:00:00+00:00,no2,0.0112,40.85355,-73.9661,Fort Lee Near Road

In [11]:
aq.to_csv("openaq.csv", index=False)